language: node_js
node_js:
- "7"  # nodejs的版本
sudo: required
branches:
  only:
  - blog_source  # 设置自动化部署的分支
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
#- npm install -g hexo
#- npm install -g hexo-cli
# 将xxxxxxxxxxx替换上面生成的内容
# 这里面的文件路径可根据自己的情况进行修改
# 解密id_rsa_blog.enc 输出到.ssh/文件夹下，命名为id_rsa
- openssl aes-256-cbc -K $encrypted_9bd71818ba76_key -iv $encrypted_9bd71818ba76_iv -in .travis/id_rsa_blog.enc -out ~/.ssh/id_rsa -d
# 设置id_rsa文件权限
- chmod 600 ~/.ssh/id_rsa
# 添加ssh密钥
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
# 添加ssh配置文件
- cp .travis/ssh_config ~/.ssh/config
# 设置github账户信息
- git config --global user.name "mike" #设置github用户名
- git config --global user.email "2758566@qq.com" #设置github用户邮箱
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean && hexo g -d
